$( document ).ready(function() {

  function quem_e_voce(){
    return ['Embaixatriz decapolitana','Herói do povo do Distrito da Terra Vermelha','Militante das Hexades','Mercadora aventureira safraniana','Pregadora da Cidade Esmeralda','Botanista burguesa das Terras Vermelhas','Artista intinerante laranjenha','Pastora nômade das Terras Verdes','Pirata exilada liberal','Anã Salgada mineradora','Imigrante do clima das Terras Amarelas','Inquisitora arcoirense infiltrada','Estudante dos magos púrpuras','Nobre turista diletante','Nobre azulita exilada','Cultista celeste secreta','Exilada política revolucionária violetense','Cantora cortesã laranjenha','Monja contadora metropolitana','Anã volkan a diesel','Armadilheira tocada-pelos-elfos','Engenheira das estepes bem estabelecida','Sacerdote do vinho vampiro','Anarquista púrpura cinocéfalo','Visionária lunática meio-linga','Herói bárbaro do matagal','Industrialista do ouro preto','Curandeira pedinte da Cidade Violeta','Arqueóloga independente','Velha tutora urbana','Invocadora exótica das terras selvagens','Maga pescadora','Caçadora de ruínas Safiriana','Caçadora de demônios','Advogada necromântica da Flor Engrenagem','Rancheira herege do povoado','Escrava espiã dissecada','Bruxa da montanha da lua','Inventora sindicalista das Meia-ilhas','Caçadora de máquinas geral do sindicato'];
  }

  function por_que_estrada(){
    return ['Enviada por uma corporação sinistra','Tem sonhos em que o mundo acaba','Memórias de sangue de um grande patrimônio','À procura de um livro-caixa desaparecido','Em busca de novas pessoas para converter','Ouviu rumores de um fabuloso autofabril','Encontrou uma pista sobre a amortalidade','Recebeu ordens de uma voz descorporificada agourenta','Mapa para chegar a um aerólito sem dono','Alma da pessoa amada foi roubada por um horror','Histórias de uma planta secreta curativa','Presságios de um demônio máquina mortal','Perseguida por inimigos que a adoram','O vagão perdido de sua avó','Irmão foi preso a um ba-zumbi','Recebeu um convite de uma mestra escultora de ossos','Deverá entregar um comunicado de herança para um conde','Busca uma cura para a doença que matou seu filho','Bíblia biomântica em uma biblioteca perdida','Pagar dívidas ao agiota','Visões do mundo acabando em uma tempestade de fogo','Deve levar a uma princesa uma pérola inestimável','Perseguindo um vilão do espaço','Mente interligada a um senciente moribundo','Sonhos de um mundo perdido todas as noites','À procura de um corpo protético para sua mãe','Recebeu ordens do golem do clã','Seguindo um explorador rival','Investigando pistas do grande esquecimento','Possuída por um demônio na infância','Em busca de aliados para começar uma revolução','À procura de novas terras para uma tribo perdida','Quis viajar depois de encontrar um vidente','Pura ganância industrial','Está decidida a erradicar uma doença incapacitante','Encontrou o testamento de um deus morto','Perseguida por fúrias e por um destino sombrio','Visões de glória e renascimento','Sentiu uma grande inquietação após ler um livro de metal'];
  }

  function comeca_com(){
    return ['Uma vértebra feita de metal escuro','Metade de um crânio de porcelana branca','Um tijolo verde que brilha e emana calor como uma vela','Uma garrafa cor-de-rosa com um espírito cantor','Três besouros mecânicos com gemas nos olhos','Uma preciosa tabutela de plástico amarela com quatro verdades','Um livro prateado incitando à revolução','Um rubi não lapidado contendo um holograma régio','Pérola vermelha entalhada de um comerciante linga','Pinturas de um belo litoral ciano','Um osso violeta cristalizado em chamalma','Estrela de cobre gravada com uma quintilha sacana','Quatro engrenagens de latão oriundas de um moinho de almas','Um cérebro de rato positrônico empoeirado, guardado em uma caixa de cristal','Uma pequena flor de lavanda que não murcha','Um disco translúcido de força do tamanho de um prato','Líquen curativo esverdeado, cultivado em um vaso de cerâmica','Manual de autos, com anotações nas margens','Uma garrafa térmica inoxidável com vinho tinto','Um vidro de protetor solar para vampiros','Necróculos de platina que permite ver desmortos','Um pequeno mevo peludo que ri quando acariciado','Cavalo mecânico com manchas de ferrugem','Uma caixa de personalidade de cristal, usada para criar ka-zumbis','Uma pedra amarelo-alaranjada que não pesa — um aerólito','Uma mão mecânica azul e branca','Um dente de quartzo retirado de um verme espacial','Uma pipa animada e peluda de quitina','Um cacto carmim que expele gotas de sangue','Monóculo de engrenagens com pequenas fendas','Sete fios inquebráveis de prata','Um citrino da alma, com um terço da alma de um Herói','Uma cabaça fetiche com búzios','Um elmo de bruxo azul-petróleo, decorado com três listras brancas','Uma capa amarela de pura seda de aço','Jogo de talheres de plástico que não envelhecem','Um chifre de unicórnio arco-íris','Um cubo cinza que pesa cinco vezes mais do que chumbo','Uma xícara verde-limão à moda Cebola e Crânio','O coração cristalino de um vila','Um cajado vermelho feito de antigas pistolas fundidas'];
  }

  function pericias(){
    return ['Farmacologia','Arqueologia','Caça de grandes animais','Biomecânica','Trato com felinos','Química','Produção de café','Comédia','Contorcionismo','Cura por Cristais','Fabricação de dados','Pesca','Forrageio','Trabalho com armas','Alucinações','Cultivo de leguminosas','Marketing','Construção','Trato com Mulas','Narco-herbalismo','Navegação','Necromancia','Cavalgada Neonmade','Velhatec','Organização de malas','Fitomancia','Lucro','Gerenciamento de projetos','Protocolo','Teatro de Marionetes','Direção Defensiva','Luta performática','Manipulação de almas','Espeleologia','Contação de histórias','Cirurgia','Planejamento tático','O Mercado','Guerra','Tecnologia mevânica'];
  }

  function papel(){
    return ['Agronomista','Embaixador','Antropólogo','Arqueólogo','Artífice','Assassino','Banqueira','Nobre Bárbaro','Ladrão de corpos','Botanista','Viajante alquebrado','Cartógrafo','Chefe','Golpista','Cortesão','Cultista','Heroí Amaldiçoado','Andarilho Amaldiçoado  ','Dentista','Diletante','Doutor','Farmacêutico','Parasita Ancião','Emissário','Engenheiro','Animador','Escravo foragido','Eunuco','Exilada','Exploradora','Herói Caído','Herói do Povo','Fugitivo','Aventureiro elegante','Operador de Golem','Representante de Guilda  ','Mestre de guilda','Pastor','Hegere','Historiador','Guerreiro Santo','Caçadora','Mau presságio','Inquisidor','Inspetora','Investigador','Máquina-Humana','Mestre Artesão','Mecânico','Mercenário','Mercadora','Príncipe Mercador','Mensageiro','Mineira','Caçador de Monstros','Musicista','Necromante','Nobre','Nômade','Órfão','Pintora','Patrulheiro','Mascate','Peregrino','Portador da praga','Possuída','Sacerdote','Profeta (louca)','Profeta (real)','Assaltante','Saqueador','Refugiada','Pesquisador','Catadora','Cientista','Canalha','Batedor','Escultora','Xamã','Pastora','Escravagista','Soldado','Feiticeiro','Vendedora de Temperos','Espião','Invocadora','Ladrão','Viciada em Adrenalina','Viajante do Tempo','Latoeira','Viajante Ultra','Veículo Desmorto','Prole Vila','Infiltrador Mevo','Bruxo','Vampiro do Vinho','Bruxa','Mago','Lenhador','Zoóloga'];
  }

  function nome_um(){
    return ['Almir','Amaro','Amberto','Arcia','Arnasto','Astia','Belina','Benito','Berengar','Boko','Cuoia','Dalani','Dana','Davor','Delno','Depico','Desena','Dolce','Enrike','Erena','Ernedar','Estato','Estrela','Farfalon','Fina','Galavar','Girolamo','Girondo','Goria','Hotena','Ipa','Isizia','Izabera','Jalosti','Jernina','Jeuna','Jion','Karlo','Karnelia','Kasciuto','Katyu','Klesana','Krasna','Kenzo','Lateria','Leonti','Leuterio','Leva','Lisak','Liuti','Loma','Maurizia','Mehaci','Mirena','Mirodar','Nebesa','Noturna','Ombra','Opoya','Paprizio','Piskero','Plania','Prima','Rasclana','Rion','Robais','Rocio','Rodina','Rosa','Rostolf','Rumen','Samorok','Sangua','Sarca','Sciaca','Scikapfo','Scura','Selesta','Sentena','Severa','Sima','Sinon','Siya','Sodoba','Sulmar','Tamke','Teredo','Tesana','Tori','Trista','Urna','Vedya','Velena','Vera','Vero','Volek','Yako','Yasna','Yesen','Yeza'];
  }

  function nome_dois(){
    return ['Al Piz','Artifiziale','Azul','Bodizie','Carnemante','Celestini','Circolangolo','Cosmonauta','d`Aranje','da Pastafari','Dabasso','de Bianco','de Carmico','de Chouet','de Giallo','de Karavan','de Nero','de Safranj','de Selezione','de Serpens','Decapolitano','del Mar','di Alto','di Dormenta','di Mesa','di Verde','Donaplenum','Formatore','Fustin','Hexadni','i`Buyeni','i`Creati','i`Fortun','i`Grati','i`Liberat','i`Mertu','i`Mutabili','i`Novi','i`Orca','i`Profunt','i`Sacer','i`Syan','i`Verdenti','il`Arivat','Malapensa','Marmoresti','Mecanizio','Mentat','Mercandili','Metropolitano','Moderni','Nagori','Nascosti','Nauta','Nebodari','o`Sovobo','od Cusciare','od Jiab','od Kaniona','od Kojina','od Mise','od Notte','od Petiz','od Planye','od Playe','od Poti','od Setroya','od Sode','od Vina','od Visocco','od Vode','od Vulkan','od Yedeni','Odlingi','Ossomangio','per Ambulati','per Nascieni','per Velizi','po Viladrini','Purpúreo','Raziunar','ri Svelti','Rinasciti','Rudeni','Rumeni','s`Esmeralda','Semolingi','Seruleo','Setvareni','Tergestini','Terracotan','a Azul','a Laranja','a Púrpura','o Vermelho','o Amarelo','Travini','Violo','Vites','za Zidovi'];
  }

  function historia(){
    return ['Bondoso e conhecedor. Tem um baú de viagem cheio de horrores.','Cauteloso, apavorado até. Acredita que está sendo perseguido por demônios.','Orgulhoso e pomposo. Clama grandes feitos, na verdade é um inepto.','Bêbado magnífico. Bebe para evitar um segredo cósmico.','Lunático. Fica literalmente doido quando vê a lua.','Cansada do mundo e desesperançada, segue em uma obstinada falta de imaginação.','Incrivelmente habilidosa, mas não bate muito bem. Nunca mencione a guerra.','Frágil, com um desespero silencioso. Procura um amigo perdido, mas irá falhar.','Animado e brilhante. Encontrou uma máquina secreta na vastidão.','Envergonhado e taciturno. Sonhos enterrados na poeira há séculos.','Alto. Quer dançar com o povo das flores e sentir amor o tempo todo.','Forte e severo. Emancipado das questões mundanas, segue uma sentença superior.','Melancólica. Escuta um som muito cruel e sabe que tempos difíceis virão.','Duas-caras. Trabalhará duro para se integrar antes de dar um golpe.','Obcecado com o caramujo preto. Está convencido de que o sangue da criatura é uma panaceia.','Sujo, porém devoto. Se sujeira fosse santidade, ele seria um santo.',
    'Queima em raiva. Justa, porém mal guiada.','Um pecador sob a pele de um anjo. Uma criatura da noite.','Alegre e brilhante. Aterrorizado quando dominado por visões apocalípticas.','Alguém soturnamente agradável. Reclamona e carente, embora muito competente.','Rude e grosseiro. Em uma jornada muito difícil e importante.','Grosseiro e ofensivo. Esconde um coração de ouro.','Triste e perturbada. Carrega o peso de uma grande perda.','Desesperançado e desolado. Tem o passado enterrado nas mentiras de um futuro glorioso.','Calma e fofa. Os olhos brilham enquanto zomba da rotina diária.','Ansioso. Se recusa a olhar para cima e tem medo das estrelas. Olhos o acalmam.','Assustador e quieto. Desenha sigilos perturbadores quando ninguém está olhando.','Gentil e delicado. Se recusa a ser levado a qualquer decisão ou acordo.','Uma tola. Usa charme e um sorriso pronto para mascarar um poço profundo de incerteza.','Brutal e sem coração. Perdeu a mãe para um estranho poeta itinerante.','Tagarela e inofensiva. Se transforma em uma besta quando exposta à lua.','Cheia de piadas. Apavorada com qualquer metal e sussurra sobre máquinas devoradoras.',
    'Pegajoso e servil. Um cogumelo entre humanos, mas não é um cultista.','Descuidado e negligente. Obcecado com fórmulas falhas.','Nerd e ofensiva. Clama ser uma vítima de infortúnios obscuros.','Língua ferina mas, no fundo, uma boa pessoa. Ferido pelas circunstâncias.','Ridiculamente devoto. Recita versos para evitar encarar verdades duras.','Calculista e ecumênico. Clama às divindades para conseguir o que quer.','Fraca, mas orgulhosa. Se agarra a pequenas vitórias com uma necessidade digna de pena.','Vigoroso. Enfrenta uma falsa profecia com grande tranquilidade.','Compulsivamente competitivo. Sempre precisa ganhar.','Magoada e retraída. Precisa encarar uma tarefa urgente, mas se recusa.','Estressada. Sobrecarregada de responsabilidades, não vai resistir muito tempo.','Lânguido. Naturalmente relaxado e calmo.','Muito profunda. Insights surpreendentes se escondem atrás de palavras simples.','Muito reprimido. Esconde os desejos pessoais atrás de uma barreira de polidez.','Suspeito e acusador. Projeta seus próprios medos e crimes em outras pessoas.','Cansada e prestes a pirar. Odeia a todos quase quanto odeia a si.',
    'Violento. Usa de agressividade para mascarar sua própria solidão.','Solitário e tímido. Morre de medo de se abrir.','Traumatizada e raivosa. Confusa sobre como quebrar o ciclo de dor.','Iludido. Se recusa a aceitar que qualquer coisa possa estar dando errado.','Paranoico. Está convencido que há lingitas perseguindo-o.','Perseguida. Seguida por criaturas vis fora do espaço-tempo','Alcoólatra divertido que nega os próprios problemas.','Chorosa e ineficaz. Secretamente violenta e cruel.','Cruel e insensível. Só quer saber de si.','Manipilativo e perigoso. Convencido de que é um líder escolhido.','Passional e expansiva. Está trazendo um mundo melhor.','Vingativo. Consumido por ódio depois de testemunhar crimes horríveis.','Curiosa. Obcecada a descobrir a origem de suas raízes.','Tendência à intelectualização. Recusa a envolver-se em problemas. Ao invés disso, começa a enumerar todas as técnicas que podem ser usadas como solução.','Bom humor e devoção. Ri diante da ideia da vinda de uma Grande Entidade Tentacular.','Falso e hipocondríaco. Está convencido de que vai morrer em breve (não vai).',
    'Megalomania. Elabora grandes planos para a Torre do Poder Absoluto.','Visionária balbuciante. Desastrada, mas capaz de grandes feitos.','Misericordioso e capaz. Procura ajudar um jovem valoroso.','Nervosa. Viu uma criatura misteriosa. Duas vezes.','Tediosa como um tijolo. Honesta, boa e sem graça. Está fazendo algo muito bom.','Sarcástico, divertido e um traidor.','Assassino amigável. Tem um mapa de tesouro enterrado em um orfanato.','Agressiva e animada. Disposta a minimizar qualquer risco.','Animado, porém sinistro. Tudo indica que tem um lado sombrio.','Incrivelmente bem informada, mas inumana. Felizmente muito passiva.','Malandro e adorável. E também muito insensível e ambicioso.','Voz e andar engraçados, mas habilidosa em batalha. Carrega consigo um segredo sem valor.','Chocante e áspero. Leal e redondamente errado sobre uma facção próxima.','Comprometida por uma facção local, inabalável em sua devoção.','Frio e lógico, perito em combate desarmado, guiado por impulsos estranhos.','Metódica e severa, marcada por mil batalhas, agora leal a um senhor distante.',
    'Raiva. Muita raiva. Abatido, aparentemente amaldiçoado. Tem um nêmesis.','Sorridente e encantadora, não parece fazer nada errado. Embora faça sim.','Astuto e servil, acredita genuinamente que está ajudando o mundo.','Enlouquecida. Certa de que é uma alienígena em uma casca mortal. Talvez ela seja?','Rápido em julgar. Portador de uma maldição contagiosa.','Surpreendentemente carismática, porém ignorante do próprio charme. Seguida por um cortejo. Influenciável?','Viciado em drogas e herdeiro secreto de uma fortuna encharcada de sangue.','Jovem e inexperiente, mas o foco de uma grande profecia.','Fala alto e dominador. Injustiçado apenas uma vez, e só uma vez.','Incompreensível e estranha. Uma heroína de uma terra distante?','Rebelde, insensível e duro. Devotado a uma boa causa.','Provocante e brincalhona. Uma maga sombria às escondidas.','Rude e expansiva. Muito expansiva. Além disso, muito carinhosa e dedicada, procurando um mestre. Veja, ela tinha um mestre. Um grande mestre. Assunto muito secretivo.','Geniosa como um mula, e tão sábia quanto. Ela é a peça principal de um culto.',
    'Tem medo do escuro e está convencido de que as colinas têm olhos. E elas realmente têm.','Bobo além da imaginação. E também está completamente errado sobre monstros.','Cleptomaníaca. Sofre a maldição de se degenerar em uma besta violenta.','Brigão e nostálgico. Sente falta dos dias de antes e ajudaria a trazê-los de volta.','Imprudente e enganador de uma forma amigável. Ofendeu as pessoas erradas.','Brincalhona, mas triste por dentro. Amaldiçoada por uma distante divindade maquínica a nunca morrer.'];
  }

  function cor(){
    return ['Ira','Vigilante','Repugnante','Enlutado','Maravilhamento','Terror','Admiração','Alegria','Declínio','Queda','Agressão','Desprezo','Remorso','Desaprovação','Fascínio','Submissão','Amor','Otimismo','Esperança','Desespero','Avô','Pai','Tia','Tio','Prima','Irmão mais novo','Criança','Sobrinho','Sobrinha','Neta','Adoção','Juramento','União de Sangue','Espírito','Crescimento','Modificação','Reescrever','Mudança','Rivalidade','Bravata','Profissional','Amorosa','Status','Riqueza','Parental','Irmão mais velho','Amigável','Profana','Consumo','Destruição','Adultério','Roubo','Enganação','Assassinato','Traição','Sedução','Cativeiro','Tortura','Assistência','Proteção','Medo','Tédio','Confiança','Distração','Fúria','Interesse','Serenidade','Irritação','Arrependimento','Aceitação','Infância','Amizade','Escolaridade','Militar','Aprendiz','Viagem','Hobby','Trabalho','Atribulação','Destino','Prometido','Casamento','Perda','Morte','Lembranças','Curiosidade','Preguiça','Determinação','Dominação','Fascinação','Desencantamento','Investigação','Ciência','Sem significância','Espaço','Loucura','Meditação','Paz','Iluminação','Transcendência'];
  }
  

  $('#btnGerarPersonagem').click(function(){

    var pericia = exclusiveRandom(pericias(),3);

    $('.boxNPCs').html(
    '<div class="boxNPC">'+
      '<p><b>Quem é você?'+'</b>'+
      '<br>'+random(quem_e_voce())+'</p>'+
      '<p><b>Por que você está na estrada?'+'</b>'+
      '<br>'+random(por_que_estrada())+'</p>'+
      '<p><b>Você começa com...'+'</b>'+
      '<br>'+random(comeca_com())+'</p>'+
      '<p><b>Perícias'+'</b>'+
      '<br>'+pericia[0]+', '+pericia[1]+' e '+pericia[2]+'</p>'+
    '</div>');

    $('.boxNPC').css({'border': 'solid 1px black', 'border-radius': '5px', 'padding': '10px', 'margin': '10px', 'margin-left': '0px', 'max-width': '550px', 'box-shadow': '5px 5px 10px lightgrey'});

  });

  $('#btnGerarNPC').click(function(){

    $('.boxNPCs').html(
    '<div class="boxNPC">'+
      '<center><h4>'+random(nome_um())+' '+random(nome_dois())+'</h4></center>'+
      '<p><b>Papel:</b> '+random(papel())+
      '<br><b>Cor:</b> '+random(cor())+'</p>'+
      '<p><b>História:</b> '+random(historia())+'</p>'+
    '</div>');

    $('.boxNPC').css({'border': 'solid 1px black', 'border-radius': '5px', 'padding': '10px', 'margin': '10px', 'margin-left': '0px', 'max-width': '550px', 'box-shadow': '5px 5px 10px lightgrey'});

  });

  setTimeout(function() {
      $("#btnGerarPersonagem").trigger('click');
  },10);

});